x-app-common: &app-common
  build:
    context: .
    dockerfile: app/Dockerfile
    target: dev
  volumes:
    - ./app:/usr/src/app
    - ./tests:/usr/src/tests
    - ./pyproject.toml:/usr/src/pyproject.toml
    - ./uv.lock:/usr/src/uv.lock
    - ./alembic.ini:/usr/src/alembic.ini
  depends_on:
    db:
      condition: service_healthy


services:

  db:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: db_counsy
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-counsy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-counsy}
      - POSTGRES_DB=${POSTGRES_DB:-con}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ./test_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U counsy -d con" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web_counsy
    <<: *app-common
    command: uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8010
    env_file:
      - ./app/core/.env
    ports:
      - 127.0.0.1:8010:8010
    environment:
      - PYTHONPATH=/usr/src
      - DB__URL=${DB__URL:-postgresql+asyncpg://counsy:counsy@db:5432/con}
      - DEBUG=${DEBUG:-True}

  redis:
    volumes:
      - redisdata:/data
    image: redis:8.10.1-alpine
    container_name: redis_counsy
    ports:
      - 127.0.0.1:6379:6379
    expose:
      - 6379
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    <<: *app-common
    container_name: worker_celery
    command: uv run celery -A app.workers.celery_app:celery_app worker --loglevel=info
    env_file:
      - ./app/core/.env
    environment:
      - PYTHONPATH=/usr/src
      - DB__URL=${DB__URL:-postgresql+asyncpg://counsy:counsy@db:5432/con}
      - REDIS__URL=${REDIS__URL:-redis://redis:6379/0}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  embedder:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: embedder_counsy
    command: --model-id intfloat/multilingual-e5-large
    volumes:
      - tei_data:/data

  test:
    container_name: test_counsy
    <<: *app-common
    command: uv run pytest
    env_file:
      - ./app/core/.env
    environment:
      - PYTHONPATH=/usr/src
      - TEST_DB_URL=${TEST_DB_URL:-postgresql+asyncpg://counsy:counsy@db:5432/con_test}
    profiles:
      - test

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
  tei_data:
    driver: local
