"""add doc_status to documents

Revision ID: 4b726628cd7d
Revises: af21fe7af834
Create Date: 2026-09-11 13:40:57.918369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b726628cd7d'
down_revision: Union[str, Sequence[str], None] = 'af21fe7af834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_status')
    # ### end Alembic commands ###
