"""add embedding to chunks

Revision ID: af21fe7af834
Revises: c5300dbfe4b3
Create Date: 2026-08-31 14:27:27.109172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'af21fe7af834'
down_revision: Union[str, Sequence[str], None] = 'c5300dbfe4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
